import { NextRequest, NextResponse } from "next/server"
import { put, head } from "@vercel/blob"
import { getTrackedTokens } from "@/lib/get-tracked-tokens"
import type { ResearchReport } from "@/lib/types/research"
import { env } from "@/lib/env"
import { generateWeeklyReportNarrative } from "@/lib/research/openai"

export const runtime = "edge"
export const dynamic = "force-dynamic"

/**
 * Get ISO week number and format as YYYY-Www
 */
function getISOWeek(date: Date): string {
  const target = new Date(date.valueOf())
  const dayNr = (date.getDay() + 6) % 7
  target.setDate(target.getDate() - dayNr + 3)
  const firstThursday = target.valueOf()
  target.setMonth(0, 1)
  if (target.getDay() !== 4) {
    target.setMonth(0, 1 + ((4 - target.getDay() + 7) % 7))
  }
  const weekNumber = 1 + Math.ceil((firstThursday - target.valueOf()) / 604800000)
  return `${target.getFullYear()}-W${weekNumber.toString().padStart(2, "0")}`
}

/**
 * POST /api/research/generate/weekly
 * Auto-generates weekly market insights and publishes to Blob
 * Protected by CRON_SECRET for Vercel Cron Jobs
 */
export async function POST(request: NextRequest) {
  try {
    // Security: Validate CRON_SECRET
    const authHeader = request.headers.get("authorization")
    const expectedSecret = env.CRON_SECRET || env.RESEARCH_GENERATE_SECRET

    if (!authHeader || authHeader !== `Bearer ${expectedSecret}`) {
      console.log("[v0] Unauthorized weekly report generation attempt")
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    // Get current week
    const today = new Date()
    const weekSlug = getISOWeek(today)

    // Check if this week's report already exists (idempotency)
    const blobPath = `research/weekly/${weekSlug}.json`
    try {
      const existing = await head(blobPath)
      if (existing) {
        console.log(`[v0] Weekly report for ${weekSlug} already exists, skipping`)
        return NextResponse.json({
          success: true,
          message: "Report already exists",
          week: weekSlug,
          url: existing.url,
        })
      }
    } catch {
      // File doesn't exist, continue generation
    }

    console.log(`[v0] Generating weekly report for ${weekSlug}`)

    // Fetch market data
    const tokens = await getTrackedTokens()

    // Analyze weekly trends
    const topGainers = tokens
      .filter((t) => (t.volumeChange24h || 0) > 0)
      .sort((a, b) => (b.volumeChange24h || 0) - (a.volumeChange24h || 0))
      .slice(0, 5)

    const topPerformers = tokens
      .sort((a, b) => (b.solradScore || 0) - (a.solradScore || 0))
      .slice(0, 5)

    const emergingTokens = tokens.filter(
      (t) => (t.solradScore || 0) >= 70 && (t.volume24h || 0) > 100_000 && (t.volume24h || 0) < 1_000_000
    ).slice(0, 3)

    const totalVolume = tokens.reduce((sum, t) => sum + (t.volume24h || 0), 0)
    const avgScore = tokens.reduce((sum, t) => sum + (t.solradScore || 0), 0) / tokens.length

    // Try OpenAI generation first
    const aiNarrative = await generateWeeklyReportNarrative({
      week: weekSlug,
      totalTokens: tokens.length,
      totalVolume,
      avgScore,
      topGainers: topGainers.map((t) => ({
        symbol: t.symbol,
        volumeChange: t.volumeChange24h || 0,
        volume: t.volume24h || 0,
      })),
      topPerformers: topPerformers.map((t) => ({
        symbol: t.symbol,
        score: t.solradScore || 0,
        volume: t.volume24h || 0,
      })),
      emergingTokens: emergingTokens.map((t) => ({
        symbol: t.symbol,
        score: t.solradScore || 0,
        volume: t.volume24h || 0,
      })),
    })

    // Generate content (OpenAI or fallback)
    let title: string
    let summary: string
    let content: string
    let tags: string[]

    if (aiNarrative) {
      // Use OpenAI-generated narrative
      title = aiNarrative.title
      summary = aiNarrative.summary
      tags = aiNarrative.tags
      content = `${aiNarrative.sections
        .map(
          (section) => `## ${section.heading}\n\n${section.bullets.map((bullet) => `- ${bullet}`).join("\n")}`
        )
        .join("\n\n")}

---

*Generated by SOLRAD Research Lab using AI analysis on ${today.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}*`
    } else {
      // Fallback to deterministic template
      console.log("[v0] Using fallback deterministic content")
      title = `Weekly Market Insights: ${weekSlug}`
      summary = `Week ${weekSlug.split("-W")[1]} analysis: ${topGainers.length} top gainers identified, ${emergingTokens.length} emerging opportunities spotted. Market average score: ${avgScore.toFixed(1)}/100.`
      tags = ["weekly", "market-insights", "trends"]
      content = `## Weekly Market Insights

### Overview

Week ${weekSlug.split("-W")[1]} of ${weekSlug.split("-W")[0]} saw **${tokens.length} tokens** tracked with **$${(totalVolume / 1_000_000).toFixed(2)}M** in 24h volume.

**Market Health Score**: ${avgScore.toFixed(1)}/100

### Top Gainers This Week

${topGainers.map((t, i) => `${i + 1}. **${t.symbol}** - Volume Change: +${(t.volumeChange24h || 0).toFixed(1)}%, SOLRAD Score: ${t.solradScore || 0}/100`).join("\n")}

### Highest Rated Tokens

${topPerformers.map((t, i) => `${i + 1}. **${t.symbol}** - Score: ${t.solradScore || 0}/100, Liquidity: $${((t.liquidity || 0) / 1_000_000).toFixed(2)}M`).join("\n")}

${emergingTokens.length > 0 ? `### Emerging Opportunities\n\n${emergingTokens.map((t) => `- **${t.symbol}**: Score ${t.solradScore}/100, moderate volume with strong fundamentals`).join("\n")}` : ""}

### Key Takeaways

- **Market Momentum**: ${avgScore >= 60 ? "Strong" : avgScore >= 40 ? "Moderate" : "Weak"} overall token quality
- **Volume Leaders**: Top tokens driving majority of trading activity
- **Risk Profile**: Continue monitoring for security vulnerabilities and liquidity risks

---

*Generated by SOLRAD Research Lab on ${today.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}*`
    }

    const report: ResearchReport = {
      type: "weekly",
      slug: weekSlug,
      title,
      date: today.toISOString().split("T")[0],
      publishedAt: today.toISOString(),
      summary,
      tags,
      author: "SOLRAD Research",
      content,
      insights: [
        {
          title: "Weekly Momentum",
          description: `${topGainers.length} tokens showed significant volume increases this week.`,
        },
        {
          title: "Quality Tokens",
          description: `${topPerformers.length} tokens maintained scores above 70, indicating strong fundamentals.`,
        },
        {
          title: "Emerging Projects",
          description: emergingTokens.length > 0 
            ? `${emergingTokens.length} emerging tokens identified with growth potential.`
            : "No new emerging projects met our criteria this week.",
        },
      ],
      keyMetrics: [
        { label: "Week", value: weekSlug },
        { label: "Tokens", value: tokens.length.toString() },
        { label: "Avg Score", value: avgScore.toFixed(1) },
        { label: "Top Gainers", value: topGainers.length.toString() },
      ],
    }

    // Publish to Blob
    const blob = await put(blobPath, JSON.stringify(report, null, 2), {
      access: "public",
      contentType: "application/json",
    })

    console.log(`[v0] Weekly report published: ${blob.url}`)

    // Update index
    try {
      await fetch(`${new URL(request.url).origin}/api/research/publish`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ report, secret: expectedSecret }),
      })
    } catch (indexError) {
      console.error("[v0] Failed to update index:", indexError)
    }

    return NextResponse.json({
      success: true,
      week: weekSlug,
      url: blob.url,
      report,
    })
  } catch (error) {
    console.error("[v0] Weekly report generation failed:", error)
    return NextResponse.json(
      { error: "Generation failed", details: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    )
  }
}
